version: '3.1'
services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgres://notesuser:notespassword@postgres:5432/notesdb
volumes:
  postgres_data: