version: '3'
services:
  nodejs-app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespassword
    ports:
      - "5432:5432"
